name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
